NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.example.org7-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.example.org7-cert.pem
    OrganizationalUnitIdentifier: peer
