---
  Organizations: 
    - 
      &keyhol 
        Name: "keyholeMSP"
        ID: "keyholeMSP"
        MSPDir: "crypto-config/peerOrganizations/keyhole.com/msp"
        AnchorPeers: 
          - 
            Host: "peer0.keyhole.com"
            port: 7051
