---
  Organizations: 
    - 
      &Org 
        Name: "Org4MSP"
        ID: "Org4MSP"
        MSPDir: "crypto-config/peerOrganizations//msp"
        AnchorPeers: 
          - 
            Host: "peer0."
            port: 7051
