---
  Organizations: 
    - 
      &Org 
        Name: "Org7MSP"
        ID: "Org7MSP"
        MSPDir: "crypto-config/peerOrganizations/test/msp"
        AnchorPeers: 
          - 
            Host: "peer0.test"
            port: 7051
