---
  Organizations: 
    - 
      &Org 
        Name: "Org7MSP"
        ID: "Org7MSP"
        MSPDir: "crypto-config/peerOrganizations/example.com/msp"
        AnchorPeers: 
          - 
            Host: "peer0.example.com"
            port: 7051
