---
  Organizations: 
    - 
      &Org 
        Name: "Org3MSP"
        ID: "Org3MSP"
        MSPDir: "crypto-config/peerOrganizations/test.example/msp"
        AnchorPeers: 
          - 
            Host: "peer0.test.example"
            port: 7051
