---
  Organizations: 
    - 
      &keyhol 
        Name: "keyholeMSP"
        ID: "keyholeMSP"
        MSPDir: "crypto-config/peerOrganizations/example.keyhole/msp"
        AnchorPeers: 
          - 
            Host: "peer0.example.keyhole"
            port: 7051
