---
  Organizations: 
    - 
      &Org 
        Name: "Org5MSP"
        ID: "Org5MSP"
        MSPDir: "crypto-config/peerOrganizations/example5.com/msp"
        AnchorPeers: 
          - 
            Host: "peer0.example5.com"
            port: 7051
