NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.-cert.pem
    OrganizationalUnitIdentifier: peer
