NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.example3.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.example3.com-cert.pem
    OrganizationalUnitIdentifier: peer
