NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.example.test-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.example.test-cert.pem
    OrganizationalUnitIdentifier: peer
